### ISSUE TITLE
Error: unknown architecture `armv5t'

### ISSUE THREAD

**Issue by Piping** [dwelch67/qemu_arm_samples#1]
Hello,

I used your build-gcc/build_arm64 to setup the toolchain.
And then when I try to run the uart01 sample, I had the following errors, can you help me out?

I appreciate.

```bash
aarch64-none-elf-as --warn --fatal-warnings -march=armv5t strap.s -o strap.o
Assembler messages:
Error: unknown architecture `armv5t'

Error: unrecognized option -march=armv5t
make: *** [Makefile:15: strap.o] Error 1
```

**Comment by dwelch67** [comment]
because that is not an aarch64 target you have to use an aarch32 basically
arm-none-eabi  or arm-something.  aarch64-whatever cannot build for that
target

cd uart01/
make
arm-linux-gnueabi-as --warn --fatal-warnings -march=armv5t strap.s -o
strap.o
arm-linux-gnueabi-gcc -c -Wall -O2 -nostdlib -nostartfiles -ffreestanding
-march=armv5t notmain.c -o notmain.o
arm-linux-gnueabi-ld strap.o notmain.o -T memmap -o notmain.elf
arm-linux-gnueabi-objdump -D notmain.elf > notmain.list
arm-linux-gnueabi-objcopy notmain.elf -O binary notmain.bin




builds fine.

**Comment by Piping** [comment]
Thanks. I was really confused few days ago about arm's naming scheme for their product.

And now I definitely know why. I download my toolchains from linaro with bare metal support and is target for both aarch64 and armv7.

One more question, how should run your notmain.bin with qemu?

I try your command in readme and it only print out usage message.

`qemu-arm -M versatilepb -m 128M -nographic -kernel notmain.bin` dont work for me.
